/* eslint-disable react/jsx-no-undef */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react';
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
           <ChakraProvider>
          <Navbar/>
          {children}
          <Footer/>
          </ChakraProvider>
     </body>
    </html>
  );
}

  //  <ChakraProvider>
  //         <Navbar/>
  //         {children}
  //         <Hero/>
  //         <Home/>
  //         <Testimonial/>
  //         <Footer/>
  //         </ChakraProvider>